# Generated by Django 5.0.3 on 2024-06-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_add_to_cart_coupon_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.shoppingcart'),
        ),
    ]
