# Generated by Django 5.0.3 on 2024-06-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_to_cart_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shoppingcart'),
        ),
    ]
