# Generated by Django 5.0.3 on 2024-06-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_add_to_cart_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='user',
        ),
    ]
